//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TabBioApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserImage
    {
        public long Id { get; set; }
        public string userId { get; set; }
        public string InternalImagePath { get; set; }
        public string ExternalImagePath { get; set; }
        public string Title { get; set; }
        public string description { get; set; }
        public Nullable<long> ImageOrder { get; set; }
        public bool IsProfileImg { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
