//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TabBioApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBio
    {
        public string Id { get; set; }
        public string Title { get; set; }
        public string Bio { get; set; }
        public string website { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
